services:
  python:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.python
    volumes:
      - user_images:/usr/src/app/public/user_images
  mongo:
    image: mongo
    env_file:
      - .env.mongo

volumes:
  user_images:
