services:
  python:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.python
    volumes:
      - user_media:/usr/src/app/public/user_media
  mongo:
    image: mongo
    env_file:
      - .env.mongo

volumes:
  user_media:
